name: CI - CMake

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '4a600e9fea71bd7872080cbb716797e04d30e6d3'

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.25.x'

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: triexporter-cmake
        path: build/Release/